# Generated by Django 3.2.3 on 2021-07-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.BooleanField(default=True, verbose_name='membership')),
                ('customer', models.CharField(default='', max_length=50, verbose_name='customer')),
                ('app_name', models.CharField(default='', max_length=50, verbose_name='app_name')),
            ],
        ),
    ]
