# Generated by Django 3.2.3 on 2021-07-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Duo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duodata',
            name='membership',
            field=models.BooleanField(default=False, verbose_name='membership'),
        ),
    ]
