# Generated by Django 3.2.3 on 2021-07-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trio', '0002_auto_20210727_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trio_data',
            name='company',
            field=models.CharField(db_column='content', default='', max_length=50, verbose_name='company'),
        ),
    ]
