# Generated by Django 3.2.3 on 2021-07-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.TextField(default='', max_length=100, verbose_name='FullName')),
            ],
        ),
    ]
